### ISSUE TITLE
How do i solve this requirement issue?

### ISSUE THREAD

**Issue by filebe777** [UndeadSec/Idisagree#1]
/Desktop/Idisagree# sudo pip3 install -r requirements.txt
Collecting discord (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7d/d2/7424dcf9c008623961acf996a3476e692752bb23b553eb28a668beee4136/discord-0.0.2.tar.gz
Collecting subproccess (from -r requirements.txt (line 2))
  Could not find a version that satisfies the requirement subproccess (from -r requirements.txt (line 2)) (from versions: )
No matching distribution found for subproccess (from -r requirements.txt (line 2))

**Comment by A1S0N** [comment]
Just ignore that
